console/urls.py
from django.conf.urls import patterns, url  # pylint: disable-msg=R0801
from console import views

urlpatterns = patterns('',
    # login function
    url(r'^auth_login$', views.auth_login, name='auth_login'),
    url(r'^logout$', views.logout, name='logout'),

    url(r'^index$', views.index, name='index'),
    url(r'^location$', views.location, name='location'),
    url(r'^rfid$', views.rfid, name='rfid'),
    url(r'^stats$', views.stats, name='stats'),
    url(r'^video$', views.video, name='video'),

    url(r'^ajax_device_list$', views.ajax_device_list, name='ajax_device_list'),
    url(r'^ajax_device_info/(?P<device_id>\d+)/$', views.ajax_device_info, name='ajax_device_info'),

)

server/urls.py
from django.conf.urls import patterns, url  # pylint: disable-msg=R0801
from server import views


urlpatterns = patterns('',
    url(r'^test$', views.test, name='test'),

    url(r'^device$', views.device, name='device'),

    url(r'^data$', views.data, name='data'),

)

smart_device/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'console.views.login', name='login'),

    url(r'^server/', include('server.urls', namespace='server')),
    url(r'^console/', include('console.urls', namespace='console')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

templates/footer.html
<div class="container">

    <div class="copy text-center">
        Copyright &copy; 2015 by <a href='mailto:rocky.qi@qq.com'>rocky</a>
    </div>

</div>

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>管理平台-主控制台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'css_includs.html' %}
    {% include 'js_includs.html' %}

    <script type='text/javascript'>
        var deviceListTable;
        $(function () {
            showDeviceList();

        });

        function showDeviceList() {
            $.ajax({
                url: '{% url "console:ajax_device_list" %}',
                type: 'GET',
                dataType: "json",
                error: function (xhr) {
                    alert('Ajax request出错,请重试.');
                },
                success: function (response) {
                    arrangeListTableData(response);
                }
            });
        }

        function showDeviceDetail(device_id) {
            $.ajax({
                url: '{% url "console:ajax_device_info" 0 %}'.replace(0, device_id),
                type: 'GET',
                dataType: "json",
                error: function (xhr) {
                    alert('Ajax request出错,请重试.');
                },
                success: function (response) {
                    arrangeInfoTableData(response);
                }
            });
        }

        function setStatusButton(rtnJsonRow) {
            var button = null;
            if (rtnJsonRow % 5 == 0) {
                button = "<a class=\"btn btn-danger btn-xs\" title=\"点击后右侧设备数据列表出现该设备详细数据\" href=\"javascript:showDeviceDetail(0);\">异常</a>".replace(0, rtnJsonRow);
            } else {
                button = "<a class=\"btn btn-success btn-xs\" title=\"点击后右侧设备数据列表出现该设备详细数据\" href=\"javascript:showDeviceDetail(0);\">正常</a>".replace(0, rtnJsonRow);
            }
            return button;
        }

        function arrangeListTableData(rtnJson) {
            if (deviceListTable) {
                deviceListTable.fnClearTable();
            } else {
                deviceListTable = $('#device_list').dataTable({
                    "oLanguage": lang,
                    "aoColumn": [
                        {"sType": "chinese-string"}, //设备名称
                        {"sType": "string"},         //设备标识
                        {"sType": "chinese-string"}, //设备备注
                        {"sType": "string"},         //软件版本
                        {"sType": "string"}          //设备状态
                    ],
                    "bLengthChange": false, //输入页数开关
                    "bPaginate": true, //分页开关
                    "bInfo": true,  //最下方info开关
                    "sDom": 'rtpi',
                    "asStripeClasses": [],
                    "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                        var sTrClass;
                        if (aData[4] % 5 == 0)
                            sTrClass = "danger";
                        else
                            sTrClass = "success";
                        $(nRow).addClass(sTrClass);
                        return nRow;
                    }
                });
            }

            for (var i = 0; i < 50; ++i) {
                var statusButton = setStatusButton(i);
                deviceListTable.fnAddData([
                    i + 1,
                    i + 2,
                    i + 3,
                    i + 4,
                    statusButton
                ], false);
            }
            deviceListTable.fnDraw();
            {#            deviceListTable.fnSort([[1, 'desc']]);#}
        }

        function arrangeInfoTableData(rtnJson) {
            console.log('info table')
        }

    </script>

</head>
<body>
{% include 'header.html' %}

<div class="page-content">
    <div class="row">
        <div class="col-md-2">
            <div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li class="current"><a href="{% url 'console:index' %}"><i class="glyphicon glyphicon-home"></i>主控制台</a>
                    </li>
                    <li><a href="{% url 'console:rfid' %}"><i class="glyphicon glyphicon-flash"></i>RFID数据</a></li>
                    <li><a href="{% url 'console:location' %}"><i class="glyphicon glyphicon-map-marker"></i>卫星定位</a>
                    </li>
                    <li><a href="{% url 'console:video' %}"><i class="glyphicon glyphicon-facetime-video"></i>视频监控</a>
                    </li>
                    <li><a href="{% url 'console:stats' %}"><i class="glyphicon glyphicon-stats"></i>报表数据</a></li>
                </ul>
            </div>
            <div class="panel-danger">
                <div class="content-box-header panel-heading">
                    <div class="panel-title">告警数据</div>

                    <div class="panel-options">
                        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
                        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
                    </div>
                </div>
                <div class="content-box-large box-with-header">
                    <table id="device_info" cellpadding="0" cellspacing="0" border="0" class="table table-hover">
                        <tbody>
                        <tr class="danger">
                            <td title="点击后右侧设备数据列表出现该设备详细数据">设备C 温度传感器 超出阈值,请检查!</td>
                            <td title="清除该告警"><i class="glyphicon glyphicon-trash"></i></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-10">
            <div class="row">
                <div class="row">
                    <div class="col-md-6 panel-info">
                        <div class="content-box-header panel-heading">
                            <div class="panel-title">设备列表</div>

                            <div class="panel-options">
                                <a href="javascript:showDeviceList();"><i class="glyphicon glyphicon-refresh"></i></a>
                                {#                                <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>#}
                            </div>
                        </div>
                        <div class="content-box-large box-with-header">
                            <table id="device_list" cellpadding="0" cellspacing="0" border="0"
                                   class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>设备名称</th>
                                    <th>设备标识</th>
                                    <th>设备备注</th>
                                    <th>软件版本</th>
                                    <th width="10%">设备状态</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>

                        </div>
                    </div>

                    <div class="col-md-6 panel-info">
                        <div class="content-box-header panel-heading">
                            <div class="panel-title">设备数据</div>

                            <div class="panel-options">
                                <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
                                <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
                            </div>
                        </div>
                        <div class="content-box-large box-with-header">
                            <table id="device_" border="0" class="table table-bordered table-hover">
                                <thead>
                                <tr class="warning">
                                    <th>传感器</th>
                                    <th>是否正常</th>
                                    <th>当前数值</th>
                                    <th>上次告警时间</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>

                            <table id="device_config" border="0" class="table table-bordered table-hover">
                                <thead>
                                <tr class="warning">
                                    <th>传感器</th>
                                    <th>阈值(最小值)</th>
                                    <th>阈值(最大值)</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>温度传感器</td>
                                    <td>1</td>
                                    <td>60</td>
                                    <td width="10%">
                                        <button class="btn btn-info btn-xs">修改</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td>湿度传感器</td>
                                    <td>1</td>
                                    <td>60</td>
                                    <td width="10%">
                                        <button class="btn btn-info btn-xs">修改</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td>震动传感器</td>
                                    <td>1</td>
                                    <td>60</td>
                                    <td width="10%">
                                        <button class="btn btn-success btn-xs">保存</button>
                                    </td>
                                </tr>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<footer>
    {% include 'footer.html' %}
</footer>

</body>
</html>

templates/location.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>管理平台-卫星定位</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'css_includs.html' %}
    <!--引用百度地图API-->
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=C5c61f3f0b4ddc40a4d76457b86cdc15"></script>
    <script type="text/javascript">
    //创建和初始化地图函数：
    function initMap(){
      createMap();//创建地图
      setMapEvent();//设置地图事件
      addMapControl();//向地图添加控件
      addMapOverlay();//向地图添加覆盖物
    }
    function createMap(){
      map = new BMap.Map("map");
      map.centerAndZoom(new BMap.Point(109.57359,35.031766),9);
    }
    function setMapEvent(){
      map.enableScrollWheelZoom();
      map.enableKeyboard();
      map.enableDragging();
      map.enableDoubleClickZoom()
    }
    function addClickHandler(target,window){
      target.addEventListener("click",function(){
        target.openInfoWindow(window);
      });
    }
    function addMapOverlay(){
    }
    //向地图添加控件
    function addMapControl(){
      var scaleControl = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});
      scaleControl.setUnit(BMAP_UNIT_IMPERIAL);
      map.addControl(scaleControl);
      var navControl = new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_LEFT,type:BMAP_NAVIGATION_CONTROL_LARGE});
      map.addControl(navControl);
      var overviewControl = new BMap.OverviewMapControl({anchor:BMAP_ANCHOR_BOTTOM_RIGHT,isOpen:true});
      map.addControl(overviewControl);
    }
    var map = document.getElementById('map');
    initMap();
  </script>
</head>
<body>
{% include 'header.html' %}


<div class="page-content">
    <div class="row">
        <div class="col-md-2">
            <div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li><a href="{% url 'console:index' %}"><i class="glyphicon glyphicon-home"></i>主控制台</a>
                    </li>
                    <li><a href="{% url 'console:rfid' %}"><i class="glyphicon glyphicon-flash"></i>RFID数据</a></li>
                    <li class="current"><a href="{% url 'console:location' %}"><i
                            class="glyphicon glyphicon-map-marker"></i>卫星定位</a>
                    </li>
                    <li><a href="{% url 'console:video' %}"><i class="glyphicon glyphicon-facetime-video"></i>视频监控</a>
                    </li>
                    <li><a href="{% url 'console:stats' %}"><i class="glyphicon glyphicon-stats"></i>报表数据</a></li>
                </ul>
            </div>
            <div class="panel-danger">
                <div class="content-box-header panel-heading">
                    <div class="panel-title">告警数据</div>

                    <div class="panel-options">
                        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
                        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
                    </div>
                </div>
                <div class="content-box-large box-with-header">
                    <table id="device_info" border="0" class="table table-hover">
                        <tbody>
                        <tr class="danger">
                            <td title="点击后直接跳转至主控制台设备数据">设备C 温度传感器 超出阈值,请检查!</td>
                            <td title="清除该告警"><i class="glyphicon glyphicon-trash"></i></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-md-10">
            <div class="row">
                <div class="col-md-3 panel-info">
                    <div class="content-box-header panel-heading">
                        <div class="panel-title">设备列表</div>

                        <div class="panel-options">
                            <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
                            <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
                        </div>
                    </div>
                    <div class="content-box-large box-with-header">
                        <table id="device_list" border="0" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>设备名称</th>
                                <th>设备备注</th>
                                <th width="10%">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="success">
                                <td>设备A</td>
                                <td>备注A-方便记忆查找使用</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备B</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="danger">
                                <td>设备C</td>
                                <td>cd6eriuweu2</td>
                                <td>
                                    <button class="btn btn-danger btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备D</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备K</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备E</td>
                                <td>cd6eriuweu2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备F</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备G</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备H</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备I</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备J</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备G</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备H</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备I</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            <tr class="success">
                                <td>设备J</td>
                                <td>b5dfsyotpk2</td>
                                <td>
                                    <button class="btn btn-success btn-xs" title="点击后右侧卫星数据出现该设备位置数据">查看</button>
                                </td>
                            </tr>
                            </tbody>
                        </table>

                    </div>
                </div>

                <div class="col-md-9 panel-info">
                    <div class="content-box-header panel-heading">
                        <div class="panel-title">卫星数据</div>

                        <div class="panel-options">
                            <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
                            <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
                        </div>
                    </div>

                    <div class="content-box-large box-with-header">
                        <div id="map" style="overflow:auto;width:100%;height:600px">
{#                            <img src={% static "images/baidu-map-demo.png" %}>#}
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<footer>
    {% include 'footer.html' %}
</footer>

{% include 'js_includs.html' %}
</body>
</html>

templates/rfid.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>管理平台-RFID数据</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'css_includs.html' %}
</head>
<body>
{% include 'header.html' %}


<div class="page-content">
<div class="row">
<div class="col-md-2">
    <div class="sidebar content-box" style="display: block;">
        <ul class="nav">
            <!-- Main menu -->
            <li><a href="{% url 'console:index' %}"><i class="glyphicon glyphicon-home"></i>主控制台</a>
            </li>
            <li class="current"><a href="{% url 'console:rfid' %}"><i class="glyphicon glyphicon-flash"></i>RFID数据</a></li>
            <li><a href="{% url 'console:location' %}"><i class="glyphicon glyphicon-map-marker"></i>卫星定位</a></li>
            <li><a href="{% url 'console:video' %}"><i class="glyphicon glyphicon-facetime-video"></i>视频监控</a></li>
            <li><a href="{% url 'console:stats' %}"><i class="glyphicon glyphicon-stats"></i>报表数据</a></li>
        </ul>
    </div>
    <div class="panel-danger">
        <div class="content-box-header panel-heading">
            <div class="panel-title">告警数据</div>

            <div class="panel-options">
                <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
                <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
            </div>
        </div>
        <div class="content-box-large box-with-header">
            <table id="device_info" border="0" class="table table-hover">
                <tbody>
                <tr class="danger">
                    <td title="点击后右侧RFID数据列表出现该设备详细数据">设备C 温度传感器 超出阈值,请检查!</td>
                    <td title="清除该告警"><i class="glyphicon glyphicon-trash"></i></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="col-md-10">
<div class="row">
<div class="row">
<div class="col-md-6 panel-info">
    <div class="content-box-header panel-heading">
        <div class="panel-title">设备列表</div>

        <div class="panel-options">
            <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
            <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
        </div>
    </div>
    <div class="content-box-large box-with-header">
        <table id="device_list" border="0"
               class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>设备名称</th>
                <th>设备标识</th>
                <th>设备位置</th>
                <th>软件版本</th>
                <th width="10%">操作</th>
            </tr>
            </thead>
            <tbody>
            <tr class="success">
                <td>设备A</td>
                <td>a4dfs1xcvz1</td>
                <td>翠华路</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-success btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">正常</button>
                </td>
            </tr>
            <tr class="success">
                <td>设备B</td>
                <td>b5dfsyotpk2</td>
                <td>小寨</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-success btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">正常</button>
                </td>
            </tr>
            <tr class="danger">
                <td>设备C</td>
                <td>cd6eriuweu2</td>
                <td>钟楼</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-danger btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">异常</button>
                </td>
            </tr>
            <tr class="success">
                <td>设备D</td>
                <td>b5dfsyotpk2</td>
                <td>小寨</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-success btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">正常</button>
                </td>
            </tr>
            <tr class="success">
                <td>设备K</td>
                <td>b5dfsyotpk2</td>
                <td>小寨</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-success btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">正常</button>
                </td>
            </tr>
            <tr class="success">
                <td>设备E</td>
                <td>cd6eriuweu2</td>
                <td>钟楼</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-success btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">正常</button>
                </td>
            </tr>
            <tr class="success">
                <td>设备F</td>
                <td>b5dfsyotpk2</td>
                <td>小寨</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-success btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">正常</button>
                </td>
            </tr>
            <tr class="success">
                <td>设备G</td>
                <td>b5dfsyotpk2</td>
                <td>小寨</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-success btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">正常</button>
                </td>
            </tr>
            <tr class="success">
                <td>设备H</td>
                <td>b5dfsyotpk2</td>
                <td>小寨</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-success btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">正常</button>
                </td>
            </tr>
            <tr class="success">
                <td>设备I</td>
                <td>b5dfsyotpk2</td>
                <td>小寨</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-success btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">正常</button>
                </td>
            </tr>
            <tr class="success">
                <td>设备J</td>
                <td>b5dfsyotpk2</td>
                <td>小寨</td>
                <td>1.1</td>
                <td>
                    <button class="btn btn-success btn-xs" title="点击后右侧RFID数据列表出现该设备详细数据">正常</button>
                </td>
            </tr>
            </tbody>
        </table>

    </div>
</div>

<div class="col-md-6 panel-info">
    <div class="content-box-header panel-heading">
        <div class="panel-title">RFID数据</div>

        <div class="panel-options">
            <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
            <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
        </div>
    </div>
    <div class="content-box-large box-with-header">
        <table id="device_info" border="0" class="table table-bordered table-hover">
            <thead>
            <tr class="success">
                <th colspan="4">设备A RFID数据</th>
            </tr>
            <tr class="warning">
                <th>序列号</th>
                <th>扫描次数</th>
                <th>上次扫描时间</th>
                <th>备注</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>温度传感器</td>
                <td>正常</td>
                <td>31.5</td>
                <td>2015-08-21 17:30:08</td>
            </tr>
            <tr>
                <td>湿度传感器</td>
                <td>正常</td>
                <td>57.9</td>
                <td>2015-08-21 17:30:08</td>
            </tr>
            <tr>
                <td>震动传感器</td>
                <td>正常</td>
                <td>0.5</td>
                <td>2015-08-21 17:30:08</td>
            </tr>
            <tr>
                <td>红外传感器</td>
                <td>正常</td>
                <td></td>
                <td>2015-07-21 10:15:33</td>
            </tr>
            <tr>
                <td>气体传感器</td>
                <td>正常</td>
                <td></td>
                <td></td>
            </tr>

            </tbody>
        </table>

    </div>
</div>
</div>

</div>
</div>
</div>
</div>

<footer>
    {% include 'footer.html' %}
</footer>

{% include 'js_includs.html' %}
</body>
</html>